name: Deploy to Firebase Hosting on push
'on':
  push:
    branches:
      - main
jobs:
  deploy_to_firebase_hosting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install 
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@79b1a830a9ae85409cb38056dd7761f6f1cb83fd
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: ${{ secrets.FB_PROJECT_ID }}
          channelId: 'just for testting sav on'
          

          #target: production # Optional, defaults to 'production'
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          FB_CLIENT_EMAIL: ${{ secrets.FB_CLIENT_EMAIL }}
          FB_PRIVATE_KEY: ${{ secrets.FB_PRIVATE_KEY }}
          FB_PROJECT_ID: "${{ secrets.FB_PROJECT_ID }}"
          FB_SERVICE_ACCOUNT: "${{ secrets.FB_SERVICE_ACCOUNT }}"